In [23]:
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

np.random.seed(5)

In [24]:
scaler = StandardScaler()

# dataset iris
iris = datasets.load_iris()
x = iris.data
y = iris.target

# Normalização 
scaler.fit(x)
x = scaler.transform(x)

sufInd = np.arange(150)
np.random.shuffle(sufInd)

In [25]:
# divisão do dataset em treino e teste
x_train = x[sufInd[:100], :]
x_test = x[sufInd[100:], :]

y_train = y[sufInd[:100]]
y_test = y[sufInd[100:]]

In [27]:
print(x_test)

[[ 1.89829664e-01 -3.62176246e-01  4.21733708e-01  3.95774101e-01]
 [ 3.10997534e-01 -1.31979479e-01  4.78571135e-01  2.64141916e-01]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.73673948e-01 -5.92373012e-01  4.21733708e-01  1.32509732e-01]
 [ 1.89829664e-01 -1.31979479e-01  5.92245988e-01  7.90670654e-01]
 [-5.25060772e-02 -8.22569778e-01  1.94384000e-01 -2.62386821e-01]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [ 1.89829664e-01 -1.97355361e+00  1.37546573e-01 -2.62386821e-01]
 [ 6.74501145e-01  9.82172869e-02  9.90107977e-01  7.90670654e-01]
 [ 1.03800476e+00 -1.28296331e+00  1.16062026e+00  7.90670654e-01]
 [ 5.53333275e-01  5.58610819e-01  1.27429511e+00  1.71209594e+00]
 [ 1.15917263e+00  3.28414053e-01  1.21745768e+00  1.44883158e+00]
 [-1.73673948e-01  1.70959465e+00 -1.16971425e+00 -1.18381211e+00]
 [-9.00681170e-01  1.70959465e+00 -1.28338910e+00 -1.18381211e+00]
 [ 1.89829664e-01 -8.22569778e-01  7.62758269e-01  5.27406285e

In [31]:
# Classificador 
clf = MLPClassifier(solver='sgd', hidden_layer_sizes=(6,), learning_rate_init=0.9, activation='logistic', max_iter=1500, random_state=1)
clf.fit(x_train, y_train)

y_pred = clf.predict_proba(x_test)
y_aux = np.argmax(y_pred, 1)

print(f'{accuracy_score(y_test, y_aux)*100} %')

98.0 %


In [32]:
print(y_test[:10], y_aux[:10])

[1 1 0 1 2 1 0 1 2 2] [1 1 0 1 2 1 0 1 2 2]
